Assessments

In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px

1. Hassan has five kinds of dogs which are husky, pitbull, shepherd, bulldog and eskimo.
Create a python program such that anyone can check if Hassan has a particular breed, if the breed is in the list of dogs print 'present' else print 'absent'. Note: use your input and conditional statements.


In [ ]:
dogs = ['husky', 'pitbull', 'shepherd', 'bulldog','eskimo']
new_dogs = input('Enter the breed')
if new_dogs in dogs:
  print('present')
else:
  print('absent')

Enter the breedbulldog
present


2. Write a python program to reverse names.
E.g aloba - abola, aishat - tahsia



In [ ]:
def reverse_name(name):
    return name[::-1]

def main():
    name = input("Enter a name: ")
    reversed_name = reverse_name(name)
    print("Reversed name:", reversed_name)

if __name__ == "__main__":
    main()

Enter a name: aloba
Reversed name: abola


3. Create a lambda function that can add two numbers and gives a result.
e.g, addition of 2 and 3 should give 5.
Use a lambda function.



In [ ]:
sum = lambda a,b : a+b
print(sum(2,3))

5


4. Write a function that calculates the area of a rectangle.



In [ ]:
def area_of_rectangle(length,width):
  return length*width

length = 10
width = 6
result = area_of_rectangle(length,width)
print(f"Area of rectangle:{result}")

Area of rectangle:60


In [ ]:
import numpy as np

np.random.seed(0)  # For reproducibility
arr = np.random.randint(1, 50, size=(5, 5))
print("Generated Numpy Array:")
print(arr)

Generated Numpy Array:
[[45 48  1  4  4]
 [40 10 20 22 37]
 [24  7 25 25 13]
 [ 2 39 40 24 47]
 [25 18 38 26 14]]


5.  How can I index 38 from the array



In [ ]:
arr[4,2]

38

6. From the array in question 5. How can I slice out [25, 25, 13], [40 , 24, 47], [38, 26, 14]


In [ ]:
arr[2:,2:]

array([[25, 25, 13],
       [40, 24, 47],
       [38, 26, 14]])

7. Create an array of zeroes of shape, (2,5)



In [ ]:
array_0s = np.zeros(shape  = (2,5))
array_0s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

8. Create an array of ones of shape (2,5)



In [ ]:
array_1s = np.ones(shape  = (2,5))
array_1s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

9. Create an array full of 6, of shape(4,4)



In [ ]:
array_full = np.full(shape = (4,4), fill_value = 6)
array_full

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

10. Create a numpy array of shape (3,3) with random integers between 1 and 100.

In [ ]:
import numpy as np
random_array = np.random.randint(1, 101, size=(3, 3))
print(random_array)

[[73 10 21]
 [81 70 80]
 [48 65 83]]


**<h1><center>Pandas Assessment<center></h1>**

**<h1>Online Food Order Dataset</h1>**

**<h1>Description:</h1>**
The dataset contains information collected from an online food ordering platform over a period of time. It encompasses various attributes related to Occupation, Family Size, Feedback etc..

**<h1>Attributes:</h1>**

**<h2>Demographic Information:</h2>**

**Age:** Age of the customer.

**Gender:** Gender of the customer.

**Marital Status:** Marital status of the customer.

**Occupation:** Occupation of the customer.

**Monthly Income:** Monthly income of the customer.

**Educational Qualifications:** Educational qualifications of the customer.

**Family Size:** Number of individuals in the customer's family.

**<h2>Location Information:</h2>**

**Latitude:**Latitude of the customer's location.

**Longitude:** Longitude of the customer's location.

**Pin Code:** Pin code of the customer's location.
Order Details:**

**<h2>Purpose:</h2>**
This dataset can be utilized to explore the relationship between demographic/location factors and online food ordering behavior, analyze customer feedback to improve service quality, and potentially predict customer preferences or behavior based on demographic and location attributes.

11. Read in the dataset

In [ ]:
df = pd.read_csv(r"/content/onlinefoods..csv")

12. Check the head of the data to get the first 10 rows

In [ ]:
df.head()

Age  Gender Marital Status Occupation  Monthly Income  \
0   20  Female         Single    Student       No Income   
1   24  Female         Single    Student  Below Rs.10000   
2   22    Male         Single    Student  Below Rs.10000   
3   22  Female         Single    Student       No Income   
4   22    Male         Single    Student  Below Rs.10000   

  Educational Qualifications  Family size  latitude  longitude  Pin code  \
0              Post Graduate            4   12.9766    77.5993    560001   
1                   Graduate            3   12.9770    77.5773    560009   
2              Post Graduate            3   12.9551    77.6593    560017   
3                   Graduate            6   12.9473    77.5616    560019   
4              Post Graduate            4   12.9850    77.5533    560010   

  Output   Feedback  
0    Yes   Positive  
1    Yes   Positive  
2    Yes  Negative   
3    Yes   Positive  
4    Yes   Positive

13. Get the statistical information about the dataset

In [ ]:
df.describe()

Age  Family size    latitude   longitude       Pin code
count  388.000000   388.000000  388.000000  388.000000     388.000000
mean    24.628866     3.280928   12.972058   77.600160  560040.113402
std      2.975593     1.351025    0.044489    0.051354      31.399609
min     18.000000     1.000000   12.865200   77.484200  560001.000000
25%     23.000000     2.000000   12.936900   77.565275  560010.750000
50%     24.000000     3.000000   12.977000   77.592100  560033.500000
75%     26.000000     4.000000   12.997025   77.630900  560068.000000
max     33.000000     6.000000   13.102000   77.758200  560109.000000

14. Check for the sum of missing values in each column

In [ ]:
df.isna().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
latitude                      0
longitude                     0
Pin code                      0
Output                        0
Feedback                      0
dtype: int64

15. Do we have duplicates in the data, if we have duplicates drop them

In [ ]:
df.duplicated().any()

True

In [ ]:
df.shape

(388, 12)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(285, 12)

16. What is the maximum Age in the dataset?

In [ ]:
df['Age'].max()

33

17. What is the minimum Age in the dataset?

In [ ]:
df['Age'].min()

18

18. What is the mean Age in the dataset?

In [ ]:
df['Age'].mean()

24.67719298245614

19. Do Males buy food online more than the Females

In [ ]:
df['Gender'].value_counts()

Gender
Male      164
Female    121
Name: count, dtype: int64

20. Do you think Singles buy food more or Married people, write a code for that

In [ ]:
df.['Marital Status'].value_counts()

Marital Status
Single               189
Married               87
Prefer not to say      9
Name: count, dtype: int64

21. Let's analyse the Feedback. Do people give positive feedbacks

22. Use the groupby function to groupby Gender and Marital Status, then see the average age.

**<h1>Visualization</h1>**

23. Use the plotly package to create a histogram for the Age column

24. Use the plotly package to create a bar chart for the Marital Status Column

25. Use the plotly package to create a bar chart for the Gender column

26. Use the plotly package to create a bar chart for the Occupation Column

27. Use the plotly package to create a pie chart for the Gender column

28. Use the plotly package to create a bar chart for the Marital Status Column, use the Gender as the legend

29. Use the plotly package to create a bar chart for the Gender column, use Feedback as the legend

30. Use the plotly package to create a bar chart for the Monthly Income Column and use the Gender for the legend

31. Create a boxplot for the Age column

32. Create a boxplot, use gender as the x axis and Age for the y-axis

33. Create a boxplot, use Marital Status as the x axis and Age for the y-axis

34. Create a Violin Plot, use Monthly Income as the x axis and Age for the y-axis

35. Create a Scatter plot, use the Latitude as x-axis and Longitude as y-axis.

36. Create a Bubble plot, use the Latitude as x-axis and Longitude as y-axis, Use the Age as the size.